dist: bionic

install:
  # Install zsh.
  - "sudo apt-get install zsh"

addons:
  artifacts:
    paths:
      - $(du -a /home/circleci/rocky/zshdb/test | grep log$ | cut -f 2 | tr "\n" ":")
    debug: true


# run the tests
script: zsh ./autogen.sh && make check
